services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./repo_tool:/app/repo_tool
      - ./repositories:/app/repositories
      - ./digests:/app/digests
      - ./.gptinclude:/app/.gptinclude
      - ./.gptignore:/app/.gptignore
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  repositories:
  digests: 