services:
  api:
    build: .
    command: fastapi dev --host 0.0.0.0 --port 8000 repo_tool/api
    develop:
      watch:
        - action: sync
          path: ./repo_tool
          target: /app/repo_tool
        - action: rebuild
          path: pyproject.toml
    ports:
      - "8000:8000"
    volumes:
      - ./repositories:/app/repositories
      - ./digests:/app/digests
      - ./.gptinclude:/app/.gptinclude
      - ./.gptignore:/app/.gptignore
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"

volumes:
  repositories:
  digests: 